#!/bin/bash
#
# ~/etc/install [DestDir]
#
set -e
set -u
#set -x

sourcedir="$(dirname $0)"
destdir="${1:-$HOME}"

echo
echo "Installing $sourcedir into $destdir"
echo

#
# install explicitly listed symlinks from ~/etc
#
symlinks=(
    bashrc
    bash_ps1
    bash_profile
    git-prompt.sh
    vimrc
    vim
    screenrc
    rpmmacros
    gitignore_global
)
echo "Install top-level symlinks ..."
for link in ${symlinks[@]}; do
    src="$sourcedir/${link}"
    dst="$destdir/.${link}"
    if [ -e "$dst" ] && [ ! -L "$dst" ]
    then
        mv -v "$dst" "$dst~"
    fi
    ln -nsfv "$src" "$dst"
done
echo


#
# install any ~/etc/local.d/****/bashrc_local_*
#
sourcedir="$sourcedir/local.d/"
echo "Install bashrc_local_* symlinks ..."
for link in $(find $sourcedir -type f -name 'bashrc_local_*')
do
    src="${link}"
    dst="$destdir/.$(basename $link)"
    if [ -e "$dst" ] && [ ! -L "$dst" ]
    then
        mv -v "$dst" "$dst~"
    fi
    ln -nsfv "$src" "$dst"
done
echo


if git --version &>/dev/null
then
    echo "Configuring global Git configuration ..."
    gitconfig="git config --replace --global"
    $gitconfig color.ui true
    $gitconfig core.excludesfile "~/.gitignore_global"
    $gitconfig log.decorate "short"
    $gitconfig alias.b  "branch"
    $gitconfig alias.br "branch"
    $gitconfig alias.ci "commit --verbose"
    $gitconfig alias.co "checkout"
    $gitconfig alias.d  "diff"
    $gitconfig alias.dc "diff --cached"
    $gitconfig alias.l  "log --oneline --graph --decorate"
    $gitconfig alias.s  "status --short --branch"
    $gitconfig alias.st "status"
    $gitconfig alias.cp "cherry-pick"
    $gitconfig push.default simple
    echo "Review changes with: git config --global --list"
else
    echo "Warning: No git found?!" >&2
fi
echo


